# This docker-compose is for local development / test only

version: '3.6'

services:
  # DB
  db:
    image: postgres
    build:
      context: .
      dockerfile: ./postgres.Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/create_tables.sql
